# Generated by Django 4.2.3 on 2023-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resturant_details',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Resturant_Name', models.CharField(max_length=255)),
                ('Location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Latitude', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Longitude', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Rating', models.FloatField(blank=True, default=None, null=True)),
                ('No_of_votes', models.IntegerField(blank=True, default=None, null=True)),
                ('True_rating', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='menu_details',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Item_det', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Resturant', models.ManyToManyField(to='search_menu.resturant_details')),
            ],
        ),
    ]
