# Generated by Django 4.2.3 on 2023-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_menu', '0002_remove_menu_details_resturant_menu_details_resturant'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_items',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Count', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
