# Generated by Django 4.2.3 on 2023-08-01 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_menu', '0003_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Search_item', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
